name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.2.2"
      - name: Publish package
        run: |
          poetry config pypi-token.pypi {{ secrets.PYPI_API_TOKEN }}
          poetry publish --build